import basics.*

fun main(args: Array<String>) {
    println("Hello World!")
    //EvenNumbers().getEvenNumbersWithFor()
    //EvenNumbers().getEvenNumberWithWhile()
    //EvenNumbers().getEvenNumberWithDoWhile()
    //EvenNumbers().getEvenNumberWithforEach()
    //OddNumbers().getOddNumberWithFor()
    //OddNumbers().getOddNumbersSample2()
    //OddNumbers().getOddNumbersSample3()
    //OddNumbers().getOddNumbersSample4()
    //OddNumbers().getOddNumbersSample5()
    //DivisorsOfNumber().getDivisorsOfNumber()
    //OddNumbers().getOddNumbersSample6()
    //EvenNumbers().getEvenNumberWithContinue()
    //PerfectNumbers().getPerfectNumbersSample()
    //PerfectNumbers().getPerfectNumbersSample2()
    //Palindrome().getPalindromeSample()
    //FibonacciSeries().getFibonacciSeriesSample()
    //FibonacciSeries().getFibonacciSeriesSample2()
    //println( FibonacciSeries().getFibonacciSeriesSample3(4))
    //FibonacciSeries().getFibonacciSeriesWithRecursive()
    //Factorial().getFactorialNumbersample()
    //Factorial().getFactorialNumberSample1()
    //Factorial().getFactorialWithRecursive()
    //PrimeNumber().getPrimeNumberSample()
    //PrimeNumber().getPrimeNumberSample2()
    //PrimeNumber().getPrimeNumberSample3()
    //ArraySamples().getArraySample()
    //ArraySamples().getArraySample2()
    //ArraySamples().getArraySample3()
    //ArraySamples().getArraySample4()
    //ArraySamples().getArraySample5()


}